# Generated by Django 2.1.4 on 2019-01-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_id', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('profile', models.CharField(max_length=200)),
                ('alias', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('access_key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
