# Generated by Django 2.1.4 on 2019-01-07 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190107_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aws_account',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='aws_account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aws_account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
